apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYjIxbGJHTm9aV1E2WjJod1gyRnNOVGxNV1VkVGEwOVRXbVJ6ZWpsMWVGaDViVUZFY25veFl6UkNPRFJhYXpSdVJnPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImV4cGVyaW1lbnRhbCI6ICJkaXNhYmxlZCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
